
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
spec:
  channel: "4.3"
  name: serverless-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: openshift-operators
spec:
  channel: "techpreview"
  name: red-hat-camel-k 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace