apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: vertx-quickstart-native
  name: vertx-quickstart-native
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: vertx-quickstart-native:latest
  postCommit: {}
  resources:
    limits:
      memory: 4Gi
  runPolicy: Serial
  source:
    contextDir: samples/vertx
    git:
      uri: https://github.com/deewhyweb/polyglot-knative.git#vertx-native-image
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: "DockerImage"
        name: "quay.io/quarkus/ubi-quarkus-native-s2i:20.1.0-java11"
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
